name: JavaScript CI

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
    - .github/workflows/js-ci.yml
    - "**/*.js"
    - "**/package{,-lock}.json"
    - .eslintrc.json

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run lint
